name: Become a Fanatic

on:
  schedule:
    - cron: '50 23 * * *'

jobs:
  fanatic:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm start
      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: fanatic-screenshot
          path: fanatic.png
